name: Build project

on:
  # manually
  workflow_dispatch:
    inputs:
      project_version:
        description: 'Project version container image will be tagged with'
        default: 'latest'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make build script executable
        run: chmod +x build-container.sh

      - name: Build and push images
        run: |
          IMAGE=$(./build-container.sh ${{ inputs.project_version }})
          docker push ${IMAGE}
